# Generated by Django 3.1.2 on 2020-10-21 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.CharField(default='positive', max_length=10),
        ),
    ]
